name: First Workflow
on: workflow_dispatch
jobs:
  first-jobs:
    runs-on: ubuntu-latest
    steps:
      - name: pringing welcome
        run: echo "Hellow World"
      - name: Exiting job
        run: echo "Exiting"
